### ISSUE TITLE
Delta Object Decode Issue

### ISSUE THREAD

**Issue by genedna** [open-rust-initiative/mega#200]
When I push `https://github.com/8go/matrix-commander-rs` to `third_parts/crates/8go/matrix-commander-rs`, I get a decode delta object error:

```bash
cargo run https
    Finished dev [unoptimized + debuginfo] target(s) in 0.90s
warning: the following packages contain code that will be rejected by a future version of Rust: buf_redux v0.8.4, nom v4.2.3
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target/debug/mega https`
HttpOptions {
    host: "127.0.0.1",
    port: 8000,
    key_path: None,
    cert_path: None,
    lfs_content_path: Some(
        "/Volumes/Data/objects/mega",
    ),
    data_source: Postgres,
}
First setting: IdGeneratorOptions { method: Some(1), base_time: Some(1582136402000), worker_id: Some(1), worker_id_bit_len: Some(6), seq_bit_len: Some(8), max_seq_num: Some(255), min_seq_num: Some(5), top_over_cost_count: Some(2000) }
2023-10-24T16:54:07.979985Z DEBUG hyper::proto::h1::io: parsed 6 headers
2023-10-24T16:54:07.980020Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-10-24T16:54:07.981941Z  INFO gateway::https: headers: {"Content-Type": "application/x-git-receive-pack-advertisement", "Cache-Control": "no-cache, max-age=0, must-revalidate"}
2023-10-24T16:54:07.988642Z DEBUG sqlx::query: summary="SELECT * FROM refs …" db.statement="\n\nSELECT\n  *\nFROM\n  refs\nwhere\n  $1 LIKE CONCAT(repo_path, '%')\n" rows_affected=1 rows_returned=1 elapsed=4.756209ms
2023-10-24T16:54:07.995563Z DEBUG sqlx::query: summary="SELECT \"refs\".\"id\", \"refs\".\"repo_path\", \"refs\".\"ref_name\", …" db.statement="\n\nSELECT\n  \"refs\".\"id\",\n  \"refs\".\"repo_path\",\n  \"refs\".\"ref_name\",\n  \"refs\".\"ref_git_id\",\n  \"refs\".\"created_at\",\n  \"refs\".\"updated_at\"\nFROM\n  \"refs\"\nWHERE\n  \"refs\".\"repo_path\" = $1\n" rows_affected=1 rows_returned=1 elapsed=5.199125ms
2023-10-24T16:54:07.995910Z DEBUG git::protocol::pack: git_info_refs response: b"001f# service=git-receive-pack\n000000824f76fa8feb4b4a2b50b168f5a2c5b064e5961185 HEAD\0report-status report-status-v2 delete-refs quiet atomic side-band-64k ofs-delta\n003d4f76fa8feb4b4a2b50b168f5a2c5b064e5961185 refs/heads/main\n0000"
2023-10-24T16:54:07.996290Z DEBUG hyper::proto::h1::io: flushed 541 bytes
2023-10-24T16:54:08.017061Z DEBUG hyper::proto::h1::io: parsed 7 headers
2023-10-24T16:54:08.017078Z DEBUG hyper::proto::h1::conn: incoming body is content-length (6582 bytes)
2023-10-24T16:54:08.017184Z DEBUG hyper::proto::h1::conn: incoming body completed
2023-10-24T16:54:08.018393Z DEBUG git::protocol::pack: init comamnd: RefCommand { ref_name: "refs/heads/main", old_id: "4f76fa8feb4b4a2b50b168f5a2c5b064e5961185", new_id: "42b2deaedbaa3146938e24d54aa3aeeb1482f9a6", status: "ok", error_msg: "", command_type: Update }, caps:[ReportStatusv2, SideBand64k]
2023-10-24T16:54:08.018639Z  INFO git::internal::pack::preload: Start Preload git objects:40
2023-10-24T16:54:08.018646Z  INFO git::internal::pack::preload:  Preloading  git objects:0
2023-10-24T16:54:08.020630Z  INFO git::internal::pack::preload: Preload time cost:2 ms
2023-10-24T16:54:08.020682Z  INFO git::internal::pack::preload: Decode the preload git object
***Git Type Counter Info***
commit:6  tree:3   blob:4  tag:0	ref_delta :12	ofs_dalta:15
base_object:13 	 delta_object:27 	

2023-10-24T16:54:08.020703Z  INFO git::internal::pack::preload: Deal with the object using 10 threads.
2023-10-24T16:54:08.021543Z DEBUG sqlx::query: summary="BEGIN" db.statement="" rows_affected=0 rows_returned=0 elapsed=180.042µs
2023-10-24T16:54:08.021909Z  INFO git::internal::pack::preload: thread begin : 42801
2023-10-24T16:54:08.021915Z  INFO git::internal::pack::preload: thread begin : 31824
2023-10-24T16:54:08.021925Z  INFO git::internal::pack::preload: thread begin : 30878
2023-10-24T16:54:08.021929Z  INFO git::internal::pack::preload: thread begin : 45686
2023-10-24T16:54:08.021929Z  INFO git::internal::pack::preload: thread begin : 34044
2023-10-24T16:54:08.021933Z  INFO git::internal::pack::preload: thread begin : 37361
2023-10-24T16:54:08.021909Z  INFO git::internal::pack::preload: thread begin : 950
2023-10-24T16:54:08.021930Z  INFO git::internal::pack::preload: thread begin : 10025
2023-10-24T16:54:08.021949Z  INFO git::internal::pack::preload: thread begin : 7451
2023-10-24T16:54:08.021986Z  INFO git::internal::pack::preload: thread id  : 31824 run to obj :0
2023-10-24T16:54:08.021988Z  INFO git::internal::pack::preload: thread begin : 64208
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
2023-10-24T16:54:08.028623Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=5.053459ms
2023-10-24T16:54:08.031698Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=8.142833ms
2023-10-24T16:54:08.031804Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=7.073125ms
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
2023-10-24T16:54:08.032603Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=7.744ms
2023-10-24T16:54:08.032716Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=7.622417ms
2023-10-24T16:54:08.033997Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=2.210166ms
2023-10-24T16:54:08.039260Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=6.309ms
2023-10-24T16:54:08.041271Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=6.923625ms
await last thread
2023-10-24T16:54:08.041311Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:19 ms
2023-10-24T16:54:08.042142Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=2.714291ms
2023-10-24T16:54:08.043550Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=517.458µs
2023-10-24T16:54:08.044486Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=4.221042ms
2023-10-24T16:54:08.046163Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=897.125µs
await last thread
2023-10-24T16:54:08.046194Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:24 ms
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:254:32:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(17), ...)
2023-10-24T16:54:08.047281Z DEBUG hyper::proto::h1::io: parsed 7 headers
2023-10-24T16:54:08.047290Z DEBUG hyper::proto::h1::conn: incoming body is content-length (6582 bytes)
2023-10-24T16:54:08.047328Z DEBUG hyper::proto::h1::conn: incoming body completed
2023-10-24T16:54:08.048259Z DEBUG git::protocol::pack: init comamnd: RefCommand { ref_name: "refs/heads/main", old_id: "4f76fa8feb4b4a2b50b168f5a2c5b064e5961185", new_id: "42b2deaedbaa3146938e24d54aa3aeeb1482f9a6", status: "ok", error_msg: "", command_type: Update }, caps:[ReportStatusv2, SideBand64k]
2023-10-24T16:54:08.048284Z  INFO git::internal::pack::preload: Start Preload git objects:40
2023-10-24T16:54:08.048288Z  INFO git::internal::pack::preload:  Preloading  git objects:0
2023-10-24T16:54:08.048491Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=590.458µs
2023-10-24T16:54:08.050074Z  INFO git::internal::pack::preload: Preload time cost:1 ms
2023-10-24T16:54:08.050084Z  INFO git::internal::pack::preload: Decode the preload git object
***Git Type Counter Info***
commit:6  tree:3   blob:4  tag:0	ref_delta :12	ofs_dalta:15
base_object:13 	 delta_object:27 	

2023-10-24T16:54:08.050096Z  INFO git::internal::pack::preload: Deal with the object using 10 threads.
2023-10-24T16:54:08.051480Z DEBUG sqlx::query: summary="BEGIN" db.statement="" rows_affected=0 rows_returned=0 elapsed=215.5µs
2023-10-24T16:54:08.051526Z  INFO git::internal::pack::preload: thread begin : 63463
thread '2023-10-24T16:54:08.051539Z  INFO git::internal::pack::preload: thread begin : 27351
tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
2023-10-24T16:54:08.051555Z  INFO git::internal::pack::preload: thread begin : 12791
2023-10-24T16:54:08.051571Z  INFO git::internal::pack::preload: thread begin : 28467
2023-10-24T16:54:08.051585Z  INFO git::internal::pack::preload: thread begin : 39810
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
2023-10-24T16:54:08.051608Z  INFO git::internal::pack::preload: thread begin : 953
2023-10-24T16:54:08.051610Z  INFO git::internal::pack::preload: thread begin : 30406
2023-10-24T16:54:08.051620Z  INFO git::internal::pack::preload: thread begin : 58736
2023-10-24T16:54:08.051628Z  INFO git::internal::pack::preload: thread begin : 18412
2023-10-24T16:54:08.051631Z  INFO git::internal::pack::preload: thread id  : 58736 run to obj :0
2023-10-24T16:54:08.051662Z  INFO git::internal::pack::preload: thread begin : 29233
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
2023-10-24T16:54:08.056711Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=4.036209ms
2023-10-24T16:54:08.057863Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=5.089041ms
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:489:5:
wrong delta decode
2023-10-24T16:54:08.058707Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=4.021459ms
2023-10-24T16:54:08.063147Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=9.421584ms
2023-10-24T16:54:08.064063Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=11.4405ms
2023-10-24T16:54:08.064947Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=3.193125ms
2023-10-24T16:54:08.066778Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=16.514125ms
await last thread
2023-10-24T16:54:08.066810Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:44 ms
2023-10-24T16:54:08.067528Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=1.620875ms
2023-10-24T16:54:08.068054Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=866.625µs
2023-10-24T16:54:08.074169Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=5.733292ms
2023-10-24T16:54:08.074343Z DEBUG sqlx::query: summary="SELECT \"git_obj\".\"id\", \"git_obj\".\"git_id\", \"git_obj\".\"object_type\", …" db.statement="\n\nSELECT\n  \"git_obj\".\"id\",\n  \"git_obj\".\"git_id\",\n  \"git_obj\".\"object_type\",\n  \"git_obj\".\"data\",\n  \"git_obj\".\"link\"\nFROM\n  \"git_obj\"\nWHERE\n  \"git_obj\".\"git_id\" = $1\nLIMIT\n  $2\n" rows_affected=0 rows_returned=1 elapsed=692.458µs
2023-10-24T16:54:08.081446Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=5.541209ms
await last thread
2023-10-24T16:54:08.081472Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:59 ms
2023-10-24T16:54:08.084429Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=19.633542ms
await last thread
2023-10-24T16:54:08.084456Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:32 ms
2023-10-24T16:54:08.086807Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=720.375µs
2023-10-24T16:54:08.089271Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=815.458µs
await last thread
2023-10-24T16:54:08.089301Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:37 ms
thread 'tokio-runtime-worker' panicked at git/src/internal/pack/preload.rs:254:32:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(36), ...)
2023-10-24T16:54:08.091477Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=489.625µs
2023-10-24T16:54:08.100274Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=6.963083ms
await last thread
2023-10-24T16:54:08.100329Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:48 ms
2023-10-24T16:54:08.103461Z DEBUG sqlx::query: summary="INSERT INTO \"mr\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"mr\" (\n    \"id\",\n    \"mr_id\",\n    \"git_id\",\n    \"object_type\",\n    \"created_at\"\n  )\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=1.382166ms
2023-10-24T16:54:08.120868Z DEBUG sqlx::query: summary="INSERT INTO \"git_obj\" (\"id\", …" db.statement="\n\nINSERT INTO\n  \"git_obj\" (\"id\", \"git_id\", \"object_type\", \"data\", \"link\")\nVALUES\n  ($1, $2, $3, $4, $5),\n  ($6, $7, $8, $9, $10),\n  ($11, $12, $13, $14, $15),\n  ($16, $17, $18, $19, $20) ON CONFLICT DO NOTHING RETURNING \"id\"\n" rows_affected=4 rows_returned=4 elapsed=15.390667ms
await last thread
2023-10-24T16:54:08.120935Z  INFO git::internal::pack::preload: Git Object Produce thread one  time cost:69 ms
```

```bash
git remote -v
local	http://127.0.0.1:8000/third_parts/crates/8go/matrix-commander-rs (fetch)
local	http://127.0.0.1:8000/third_parts/crates/8go/matrix-commander-rs (push)
origin	https://github.com/8go/matrix-commander-rs/ (fetch)
origin	https://github.com/8go/matrix-commander-rs/ (push)

git push local main
枚举对象中: 55, 完成.
对象计数中: 100% (55/55), 完成.
使用 10 个线程进行压缩
压缩对象中: 100% (36/36), 完成.
写入对象中: 100% (40/40), 6.29 KiB | 6.29 MiB/s, 完成.
总共 40（差异 27），复用 0（差异 0），包复用 0
错误：RPC 失败。curl 52 Empty reply from server
send-pack: unexpected disconnect while reading sideband packet
致命错误：远端意外挂断了
Everything up-to-date
```

**Comment by Ivanbeethoven** [comment]
This bug may be caused by an offset delta object whose base object is a ref delta object during the push operation when there is already a commit in the warehouse, and the code did not consider the error caused by this situation. I will fix this bug in the near future.Thank you for raising this issue .😁❤
